name: Update Versions JSON

on:
  schedule:
    - cron: '0 16 * * *'  # 每天 UTC 16 点，约等于北京时间 0 点
  workflow_dispatch:
  push:
    paths:
      - 'versions.json'  # 也可触发自身 workflow

permissions:
  contents: write

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run main.py
        run: |
          chmod +x main.py
          ./main.py

      - name: Commit updated JSON if changed
        id: commit_changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add versions.json
          if git diff --cached --quiet; then
              echo "No version change detected, skipping commit."
              echo "changed=false" >> $GITHUB_OUTPUT
          else
              git commit -m "Update versions.json"
              git push
              echo "changed=true" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}