name: Update Versions JSON

on:
  schedule:
    # 每天凌晨 12 点运行（shanghai 时间）
    - cron: '0 16 * * *'
  workflow_dispatch: # 支持手动触发

jobs:
 update-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x main.py
          ./main.py

      - name: Commit updated JSON (only if changed)
        id: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          
          if git diff --quiet versions.json; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
            echo "versions.json 没有变化，跳过提交。"
          else
            git add versions.json
            git commit -m "Update versions.json"
            git push
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Tag (trigger build pipeline)
        if: steps.commit.outputs.no_changes == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(jq -r '.nginx.version + "-" + .php.version' versions.json)
          echo "生成 tag: $VERSION"
          git tag $VERSION
          git push origin $VERSION