name: Update Versions JSON

on:
  schedule:
    # 每天凌晨 12 点运行（shanghai 时间）
    - cron: '0 16 * * *'
  workflow_dispatch: # 支持手动触发

jobs:
  update-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x main.py
          ./main.py

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add versions.json
          git diff --quiet || git commit -m "Update versions.json"
          git push
        env:
          # 使用仓库自动生成的 token 推送
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}